var sweety="Sweety";
var cutie="Cutie";
var temp;
console.log(" Before swap:-"+"Value1:"+sweety+"  " +"and"+"  "+"Value2:"+cutie);
temp=sweety;
sweety=cutie;
cutie=temp;
console.log("After swap:-"+"Value1:"+sweety+"  " +"and"+"  "+"Value2:"+cutie);
var num1=100;
var num2=200;
var num3=300;
var temp;
console.log(" Before swap:-"+"num1:"+num1+" ,"+"num2:"+num2+" , "+"num3:"+num3);
temp=num1;
num1=num2;
num2=num3;
num3=temp;
console.log(" After swap:-"+"num1:"+num1+" ,"+"num2:"+num2+" , "+"num3:"+num3);
